theme: jekyll-theme-cayman
title: Лекции
description: Презентации и другие материалы по программной инженерии
exclude:
  - Gemfile
  - Gemfile.lock
collections:
  lectures:
    output: true
    permalink: /:path/
  sections:
    output: true
    permalink: /:path/
defaults:
  - scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - scope:
      path: ""
      type: sections
    values:
      layout: section

