theme: jekyll-theme-cayman
title: Программная инженерия
description: Лекции, презентации и другие материалы
common_title: " | Лекции по программной инженерии"
copyright: |
  &copy; 2014–2017 Алексей Островский. 
  Тексты доступны по лицензии <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>.
exclude:
  - Gemfile
  - Gemfile.lock
collections:
  lectures:
    output: true
    permalink: /:path/
  sections:
    output: true
    permalink: /:path/
defaults:
  - scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - scope:
      path: ""
      type: sections
    values:
      layout: section

